name: Version Bump Automation

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm run ci:install

      - name: Apply version bump and push
        run: |
          npm run version-app
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "chore: version bump"
          git push
